language: en

pipeline:
 - name: WhitespaceTokenizer
 - name: RegexFeaturizer
 - name: LexicalSyntacticFeaturizer
 - name: CountVectorsFeaturizer
 - name: CountVectorsFeaturizer
   analyzer: char_wb
   min_ngram: 1
   max_ngram: 4
 - name: DIETClassifier
   epochs: 100
   constrain_similarities: true
 - name: EntitySynonymMapper
 - name: ResponseSelector
   epochs: 100
 - name: ResponseSelector
   epochs: 100
   retrieval_intent: faq
 - name: ResponseSelector
   epochs: 100
   retrieval_intent: chitchat
 - name: DucklingEntityExtractor
   dimensions: ["email", "number"]
   url: "https://duckling-server-theamineguesmi.cloud.okteto.net"
 - name: FallbackClassifier
   threshold: 0.3
   ambiguity_threshold: 0.1

policies:
 - name: MemoizationPolicy
   max_history: 1
 - name: TEDPolicy
   constrain_similarities: false
   max_history: 1
   epochs: 100
 - name: RulePolicy
   core_fallback_threshold: 0.3
   core_fallback_action_name: action_default_fallback
   enable_fallback_prediction: true
   restrict_rules: true
   check_for_contradictions: true
