version: '3.7'
services:
  duckling-server:
    image: rasa/duckling:latest
    ports:
      - 8000:8000
    networks:
      - all
  rasa-actions-server:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./utils:/app/utils
    command: rasa run actions
    ports:
      - '5055:5055'
    networks:
      - all
      
  rasa-trainer:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    user: 0:0
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      - ./models:/app/models
    command: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && echo Done Config && rasa train && chmod 777 models && model_name=ls models/*.tar.gz | head -n 1 && aws s3 cp models/$model_name s3://models-doctorsina/
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
