version: '3.7'
services:
  duckling-server:
    image: rasa/duckling:latest
    ports:
      - 8000:8000
    networks:
      - all

  rasa-trainer:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      - ./models:/app/models
    command: rasa train
    networks:
      - all

  model-uploader:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./models:/app/models
    command: sh -c "aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws s3 cp models s3://your-s3-bucket-name/ --recursive"
    depends_on:
      - rasa-trainer
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
