version: '3.7'
services:
  duckling-server:
    image: rasa/duckling:latest
    ports:
      - 8000:8000
    networks:
      - all

  rasa:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - '5005:8080' # external:internal
    networks:
      - all

  model-uploader:
    image: rasa-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./models:/app/models
    command: echo $AWS_ACCESS_KEY_ID
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
